### ISSUE TITLE
All grey text in status bar

### ISSUE THREAD

**Issue by sscotth** [atom/atom-dark-ui#31]
Today I was fixated on the white text of the grammar-status and the "Send Feedback" text. I suggest changing these to use the grey text that the other status-bar items use. Also removing the link underline would be great.

Something like this:
```css
.status-bar a {
  color: @text-color; /* #aaa */
}

.status-bar a:hover {
  color: @text-color-highlight; /* #fff */
  text-decoration: none;
}
```
