### ISSUE TITLE
Linux MATE draggin tab has a white background

### ISSUE THREAD

**Issue by freed00m** [atom/atom-dark-ui#47]
![drag](https://cloud.githubusercontent.com/assets/9461698/8268537/fa8b41ec-1789-11e5-818e-cb7c04014f2f.png)

Happens in:
Safe mode 0.209 and 0.210
Linux Mint Mate 17.1 and Debian Edition

**Comment by freed00m** [comment]
It happens in Manjaro i3wm, and everywhere I have tried it.

**Comment by simurai** [comment]
@freed00m It looks like when dragging, transparency is not supported and it uses a default white background. What happens if you switch to another theme that has rounded corners? Do you still see them white?

For the Atom dark theme, you could try to add the following to your `styles.less` file:

```less
.tab-bar .tab.is-dragging {
  box-shadow: none;
  padding: 0 10px;
  &::before,
  &::after,
  .close-icon {
    display: none;
  }
}
```

![screen shot 2015-08-28 at 12 01 38 pm](https://cloud.githubusercontent.com/assets/378023/9538183/9b80ff7e-4d7c-11e5-95d1-c026a34df18b.png)

It basically just makes the tabs square so there is no transparency needed while dragging.

**Comment by peduxe** [comment]
@simurai I have the same issue

![before](http://i.imgur.com/1DCXVu6.png)

![with your patch](http://i.imgur.com/HYqZVj8.png)

**Comment by simurai** [comment]
Ok, looks like it's not related to a theme.

What happens if you open this page http://www.html5rocks.com/en/tutorials/dnd/basics/ in Chrome, and then drag those boxes around, do you also see the white background?

![screen shot 2015-09-02 at 9 02 21 pm](https://cloud.githubusercontent.com/assets/378023/9630542/07d95e22-51b6-11e5-8aa8-c17559ab058e.png)

If it's a dragging/rendering issue in general, then the only thing I can think of is trying to make the tabs a rectangle without any shadows or rounded corners, then there might not be any white visible.

**Comment by peduxe** [comment]
@simurai yep, the same happens on that demo.

**Comment by simurai** [comment]
> @peduxe yep, the same happens with that demo, I can see the white borders.

Thanks for testing. Ok, I guess we have to wait till it gets fixed in Chromium.

In the meantime, here something to paste in your `styles.less` file that makes the tabs of Atom dark to be square and hopefully not show any white:

```less
// make tabs square to avoid white background while dargging
.theme-atom-dark-ui .tab-bar .tab {
  padding: 0 10px;
  margin: 0;
  border-radius: 0;
  background-color: #333;
  box-shadow: none;
  &::before,
  &::after {
    display: none;
  }
  .close-icon {
    margin-right: 10px;
  }
  &.active {
    box-shadow: none;
  }
}
```

**Comment by peduxe** [comment]
@simurai ![Did solve for the sides but not the top](http://i.imgur.com/R8G3bGL.png)

**Comment by simurai** [comment]
@peduxe Looks like that's the One dark theme? Maybe just try to remove the rounded corners:

```less
// make tabs square to avoid white background while dragging
.theme-one-dark-ui .tab-bar .tab {
  &::before,
  &::after,
  &.active {
    border-radius: 0;
  }
}
```

**Comment by peduxe** [comment]
Now top and left of the tab got white borders.

![](http://i.imgur.com/a7ag9YM.png)

**Comment by simurai** [comment]
What about something as radical as:

```less
.theme-one-dark-ui .tab-bar .tab {
  padding: 0;
  margin: 0;
  border: none;
  border-radius: 0;
  background: #000 !important;
  box-shadow: none;
  &::before,
  &::after {
    display: none;
  }
  &.active {
    border-radius: 0;
    background: #333 !important;
    & + .tab {
      border: none;
    }
  }
  .title {
    background: none !important;
    -webkit-mask: none;
  }
  .close-icon {
    display: none;
  }
}
```

**Comment by peduxe** [comment]
Too radical hehe

![](http://i.imgur.com/QCDzt1J.png)

**Comment by simurai** [comment]
Ok, maybe I should stop guessing and try to reproduce it. :stuck_out_tongue_winking_eye:

**Comment by simurai** [comment]
ok, this should work for One dark:

```less
.theme-one-dark-ui .tab-bar .tab.is-dragging {
  padding: 0 !important;
  margin: 0 !important;
  border: none !important;
  border-radius: 0 !important;
  background: black !important;
  box-shadow: none !important;

  .title {
    -webkit-mask: none !important;
    background: none !important;
    bottom: 0 !important;
  }

  &::before,
  &::after,
  .close-icon {
    display: none;
  }
}
```

It just replaces the dragging tab with a black saquare. Hopefully one day transparency will be supported when dragging.
